language: generic
sudo: 'required'
services:
    - docker
before_install:
    - docker build -t drtghosh/react-app -f Dockerfile.dev .
script:
    - docker run -it -e CI=true drtghosh/react-app npm run test